language: node_js
node_js:
- '4'
deploy:
  provider: npm
  email: mail@jojow.de
  api_key:
    secure: ipnBp5cgvorBrcupVa/tvZKZXBjareUJRqGfETonewCRxibg9jkJox3v3K8LCRiNpjps6cLK5/NEeb52kocNv2t30bnFNw0CVZw2nV89x8LVfa8K9SOnWRVvLJcK4zSlBLbL+qEJDNPI1nLB2grAAsHgFMjCod/wqSNsTh0xpiGkXaj/5ZiU+5yoYw+uGw7LrCJTrQjgnEooR08mgZBYiVRu3+X6MkWh/saWukIHFen23vd0YoUCK+W3ie1Rc4G4vhvDkjwtz3qC6XYG0DrKs4tyS+53YOk25l7XJwq2cwbHfEDEjDyFKLr5BNpvtUp/O84DzJt1m8WallSSIeTiR40aBvNINzjhsIn7fxfOq4p2vx1g3yoDPbu+UJIUXKbJUd1YiChfbtFBAMXCw43yX4D78enNNRb35/P9BgqiM5Q4Gtf/1otfrWYdAtfNoqXMPmbpVOYO9jyqGfTlcz0CPJMGwqHv2IYFu3Cv6csAxrtZ8tH0+3tua0sYu2XS2fQiJ8spUXzYy12CY1SGOsCTsAhly4WrrMZ1GYDmxxYaX+Plg5PP00CZ/ecGXzcUqbDPdl+PO362d6a4ebrSSUxuLiqwLegPboBqMSnueD224Nxpg1juuEJZzQ3h/SaN59POt6t4v3JHzOA7pGPVRAUIpLq9XkUVmue92GW3PlDANEI=
