language: node_js
node_js:
- '4'
deploy:
  provider: npm
  email: mail@jojow.de
  api_key:
    secure: QDnY5DjBI+ukjuOUwpz6lfN5bknI0tpeAP+WqV0qfJXwvI+iXcCqqaDEnTyzNC7BlFwXhbw3Q8sjzGG4hM1h4lE+oy/oG/mMh2rEiOFaOKV8JyE3CCUkkqzrO7N5G8k8nADPn/WJ2HYlYi2mQoI8fyTgWcYLyicSdq3QfoW7avQQ1UGNcte+UKxDn2VOyHutok/dXhtPJ3XHVZozCsUkeW30oexJq9HCtLhHhxpHENmU2CdYfuWtr2fpF+y2UsOhgsBjoF0rRVWJcaHkpM4cO6Tw69Q1wlMeXQtgxGj8/EeBO0uX3MICBBhrETdPttn1BKWb7IulesesIIl6Ca/7Q+TZ+4LcMX7JlbZTJz6dH9BCsuvFgmP47zWsn9V3bj43tkUwWOneMvWFjr7NOaoFxPRnoQouVMYPgCluHGrDiZFpYwY54MxBDwydToklOJI+ne4zScFUC/a0EU2pbq6zfCuEHMbbL1lThP/DWEChwjFftjwGhoAlZE1xavSIBTCmC4j7MrUd/FezeRP/ao8r4lsiLQgMnwYxtEKjaA6o33Pi/omaHNZkvX47JiCbpxyWwyS1pWJOg4FqgSRRYYMHAemuXQRGUj4RKDUW9AlUxewqes4LT36X8oflGR1hfXUvz8FOy5z59Mh92wmvXfdPifKDc5s9Ul14jl4szkS6q+M=
