language: node_js
node_js:
- '4'
deploy:
  provider: npm
  email: mail@jojow.de
  api_key:
    secure: LAAtpXn4NAJv4CYg9XsFQYBHvK3QRnBT2zzX8BvDoxs6ngqkPO9ZHdZ62NhhpMxTItOrZlJyg4hfkWyBladuF1hECQcOGeehoz/EWx7U76V8Fv84sWzPi11ltBr5/49z5TrX2PBp4I6y+ntEWqTUP4ntWOd3EM9EX7yoS35qxIiqwe2xfXvMLDBrllwpU+FkSiN3mjKJCIRg1XHMTZ6qTw15cD/4vAR8d64Ct6f6oQwra38OSd6P+yCsnub4YJYIojekC9r1YCr4BmpAZL86ivgLok/wD9nXgmhwSldJr7sjL/9v5cWlDrDErY7WzfMH+m4hduFdGae4iCn3pas4l6VQcLbq+6lqqc6dqlZkqHEJJY+Xn5XxbfgNs9K545lxW6LZ5f4yfDi4kpUAM0AEGR4P2i79vBEpb5CDp9dG0sKIiXkaegRpHr41Fbp020cIHkTYJsW1wbadnPzj8GInZU3ck75wliLDWiZh6hYC7pCizwBN8N65NZ41Dfjk4k9ex61a6SxL1QL+cd3N19hbBTP0zjKv6ZFahwNR0OmdtrO1ljctTkcBA9kDMPcLdERuAHzjnmdCBSpPsk0I6XfxoW/bGTPEtP1H7F2/ebpok8Yo/DQcS0jNr+lPozwM7TI0hVZkIYvJ+HrC9vjg4yRSkLXuuTCWew/bWMRyHltmn74=
